insert into regiones (id, nombre) values(1, 'America');
insert into regiones (id, nombre) values(2, 'LatinoAmerica');
insert into regiones (id, nombre) values(3, 'Asia');
insert into regiones (id, nombre) values(4, 'Europa');
insert into regiones (id, nombre) values(5, 'Africa');
insert into regiones (id, nombre) values(6, 'Medio Oriente');
insert into regiones (id, nombre) values(7, 'sudamerica');
insert into clientes (region_id, nombre, apellido, email, create_at) values (1,'Jose', 'Perez','jose@gmail.com','2018-02-01');
insert into clientes (region_id, nombre, apellido, email, create_at) values (3,'Pepe', 'Len','p@gmail.com','2018-03-02');
insert into clientes (region_id, nombre, apellido, email, create_at) values (2,'Joaquin', 'Guzman','chapo@gmail.com','2018-03-08');
insert into clientes (region_id, nombre, apellido, email, create_at) values (4,'Emigdio', 'Santamaria','luism@gmail.com','2018-07-02');
insert into clientes (region_id, nombre, apellido, email, create_at) values (7,'Eulices', 'Martinez','jb@gmail.com','2018-03-10');
insert into clientes (region_id, nombre, apellido, email, create_at) values (2,'Dalia', 'Rayos','all@gmail.com','2019-05-30');
insert into clientes (region_id, nombre, apellido, email, create_at) values (2,'Victor', 'Cortina','vj@gmail.com','2019-03-10');
insert into clientes (region_id, nombre, apellido, email, create_at) values (1,'Gerardo', 'Diaz','gerarquia@gmail.com','2018-05-11');
insert into clientes (region_id, nombre, apellido, email, create_at) values (2,'Ema', 'Ramirez','cusco@gmail.com','2017-01-10');
insert into clientes (region_id, nombre, apellido, email, create_at) values (4,'Raul', 'Perez','rau@gmail.com','2018-10-12');
insert into clientes (region_id, nombre, apellido, email, create_at) values (5,'Elma', 'Canon','moreno@gmail.com','2016-04-12');
insert into clientes (region_id, nombre, apellido, email, create_at) values (6,'Manuel', 'TorresFelix','ElOndeado@gmail.com','2018-01-10');